export const ROLE_GROUPS = {
	ADMIN: ['ADMIN', 'SR_DSTE_CO', 'DSTE', 'ADSTE', 'SSE_INCHARGE'],
	FIELD: ['SSE_SECTIONAL', 'JE_SECTIONAL', 'TECHNICIAN'],
	TESTROOM: ['TESTROOM'],
	LEGACY: ['SSE_ST_OFFICE', 'SSE_TECH', 'MAINTAINER', 'TRC', 'FIELD_ENGINEER'],
	READ_ONLY: ['AUDIT_USER', 'VIEWER'],
	SUPER: ['SUPER_ADMIN'],
};

export const ROLE_ACCESS = {
	ASSET_READ: [
		...ROLE_GROUPS.ADMIN,
		...ROLE_GROUPS.FIELD,
		...ROLE_GROUPS.TESTROOM,
		...ROLE_GROUPS.LEGACY,
		...ROLE_GROUPS.READ_ONLY,
		...ROLE_GROUPS.SUPER,
	],
	ASSET_WRITE: [
		...ROLE_GROUPS.ADMIN,
		...ROLE_GROUPS.FIELD,
		...ROLE_GROUPS.TESTROOM,
		...ROLE_GROUPS.LEGACY,
		...ROLE_GROUPS.SUPER,
	],
	TASK_READ: [
		...ROLE_GROUPS.ADMIN,
		...ROLE_GROUPS.FIELD,
		...ROLE_GROUPS.TESTROOM,
		...ROLE_GROUPS.LEGACY,
		...ROLE_GROUPS.READ_ONLY,
		...ROLE_GROUPS.SUPER,
	],
	TASK_WRITE: [
		...ROLE_GROUPS.ADMIN,
		...ROLE_GROUPS.FIELD,
		...ROLE_GROUPS.TESTROOM,
		...ROLE_GROUPS.LEGACY,
		...ROLE_GROUPS.SUPER,
	],
	TASK_APPROVE: [...ROLE_GROUPS.ADMIN, 'SSE_INCHARGE', ...ROLE_GROUPS.SUPER],
	USER_MANAGE: [
		...ROLE_GROUPS.ADMIN,
		...ROLE_GROUPS.TESTROOM,
		...ROLE_GROUPS.SUPER,
	],
	REPORT_READ: [
		...ROLE_GROUPS.ADMIN,
		...ROLE_GROUPS.READ_ONLY,
		...ROLE_GROUPS.SUPER,
	],
	ESCALATION_RUN: [...ROLE_GROUPS.ADMIN, ...ROLE_GROUPS.SUPER],
};
