-- AlterTable
ALTER TABLE "Failure" ALTER COLUMN "type" DROP NOT NULL,
ALTER COLUMN "cause" DROP NOT NULL,
ADD COLUMN "failureInTime" TIMESTAMP(3),
ADD COLUMN "isHqRepeated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "isIcmsRepeated" BOOLEAN NOT NULL DEFAULT false;
